### ISSUE TITLE
Issue with the scoring net part of D3VAE's PyTorch code  

### ISSUE THREAD

**Issue by Paandaman** [PaddlePaddle/PaddleSpatial#308]
First of all, thank you for your interesting work and for releasing the code on github!

I ran into an issue when I tried to reproduce the paper's results on the ETTh1 dataset. The issue is related to the line below:

https://github.com/PaddlePaddle/PaddleSpatial/blob/13bd2d9d8310dbe438f291caa3338d96dea964c9/research/D3VAE/d3vae_pytorch/model/resnet.py#L152

or one of the previos steps, since it only seems to work with evenly numbered batch sizes. 

To reproduce, with a fresh clone of the repository, run https://github.com/PaddlePaddle/PaddleSpatial/blob/main/research/D3VAE/d3vae_pytorch/main.py
with all arguments set to default except for the path to the dataset, the batch_size and optionally specify which gpu to use. If run with an even integer as batch_size it works:
python main.py --root_path /path/to/ETDataset/ETT-small/ --data_path ETTh1.csv --batch_size 2 --gpu 0
but if the batch_size is uneven, e.g. 1, the code crashes with the following error:
`PaddleSpatial/research/D3VAE/d3vae_pytorch/model/resnet.py", line 152, in forward
    output = output.view(-1, int(self.hw/8)*int(self.hw/8)*8*self.dim)
RuntimeError: shape '[-1, 8192]' is invalid for input of size `

**Comment by yl4467** [comment]
Hi, 
Since here we use the resnet (line 54 in ['model.py')](https://github.com/PaddlePaddle/PaddleSpatial/blob/main/research/D3VAE/model/model.py) with fixed parameters and structure to calculate the score,  so the batch size needs to be set to an even number to adapt to this network. 

If the batch size is set to an uneven number, the structure of the resnet needs to be modified as well.
